#.
#This is the color of the ground radar on the monitor
#Range: > 0
groundRadarColor = 65280
#.
#This is the scale of the grid boxes on the monitor in blocks
#Range: > 1
gridBoxScale = 100
#.
#This is the color of hostile entities on the monitor
#Range: > 0
hostileColor = 16711680
#.
#This is the color of friendly entities on the monitor
#Range: > 0
friendlyColor = 65280
#.
#This is the color of players on the monitor
#Range: > 0
playerColor = 255
#.
#This is the color of projectiles on the monitor
#Range: > 0
projectileColor = 16776960
#.
#This is the color of contraptions on the monitor
#Range: > 0
contraptionColor = 16777215
#.
#This is the color of VS2 ships on the monitor
#Range: > 0
VS2Color = 16776960
#.
#This is the color of neutral entities on the monitor
#Range: > 0
neutralEntityColor = 16777215

