#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Sat Aug 02 12:36:36 BRT 2025
a=false
farmersdelight=true
quark=true
create=true
functionalstorage=true
refurbished_furniture=true
