StartupEvents.registry('block', (event) => {
	event.create('terrafirmacivilizations:copper_mantle_ore')
        .displayName('Copper Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')

    event.create('terrafirmacivilizations:gold_mantle_ore')
        .displayName('Gold Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')

    event.create('terrafirmacivilizations:silver_mantle_ore')
        .displayName('Silver Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')
    
    event.create('terrafirmacivilizations:tin_mantle_ore')
        .displayName('Tin Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')
    
    event.create('terrafirmacivilizations:bismuth_mantle_ore')
        .displayName('Bismuth Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')

    event.create('terrafirmacivilizations:nickel_mantle_ore')
        .displayName('Nickel Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')

    event.create('terrafirmacivilizations:iron_mantle_ore')
        .displayName('Iron Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')

    event.create('terrafirmacivilizations:zinc_mantle_ore')
        .displayName('Zinc Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')
    
    event.create('terrafirmacivilizations:cryolite_mantle_ore')
        .displayName('Cryolite Mantle Ore')
        .soundType('tuff')
        .hardness(5)
        .resistance(5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('tfc:needs_colored_steel_tool')
        .tagBlock('terrafirmacivilizations:mantle_ore')
});
