
["cuffed Config"]
	#The maximum number of keys that can fit on a single key ring.
	"Maximum Keys Per Ring" = 16
	#The total number of slots in the safe.
	"Safes Slots" = 36
	#Whether or not to require players to be under 30% health to be restrained. If a player is already restrained then this setting doesn't take effect.
	"Require Low Health To Restrain" = true
	#Whether or not to allow players to spam crouch to break out of pillories.
	"Allow breaking out of the pillory" = true

	["cuffed Config"."Anchoring Settings"]
		#Whether or not to require players to be restrained to get anchored.
		"Only Restrained Players Can Be Restrained" = true
		#The maximum length of the chain when anchoring.
		"Max Chain Length" = 5.0
		#The distance when anchored entites start suffocating.
		"Suffocation Length" = 12.0
		#Whether or not players should be allowed to anchor entities to FENCES.
		"Allow Anchoring To Fences" = true
		#Whether or not players should be allowed to anchor entities to TRIPWIRE HOOKS.
		"Allow Anchoring To Tripwire Hook" = true
		#Whether or not players should be allowed to anchor entities to WEIGHTED ANCHORS.
		"Allow Anchoring To Weighted Anchors" = true

	["cuffed Config"."Nickname Settings"]
		#Whether or not nicknames should persist on death.
		"Nickname Persists On Death" = true
		#Whether or not nicknames should persist on logout.
		"Nickname Persists On Logout" = true

	["cuffed Config"."Lockpicking Settings"]
		#How much progress is gained on a successfull pick when lockpicking a PADLOCK.
		"Progress Per Pick For Breaking Padlocks" = 8
		#How much the progress-loss speeds up per pick when lockpicking a PADLOCK.
		"Speed Increase Per Pick For Breaking Padlocks" = 10
		#How much progress is gained on a successfull pick when lockpicking a REINFORCED PADLOCK.
		"Progress Per Pick For Breaking Reinforced Padlocks" = 6
		#How much the progress-loss speeds up per pick when lockpicking a REINFORCED PADLOCK.
		"Speed Increase Per Pick For Breaking Reinforced Padlocks" = 13
		#How much progress is gained on a successfull pick when lockpicking a CELL DOOR.
		"Progress Per Pick For Breaking Cell Doors" = 6
		#How much the progress-loss speeds up per pick when lockpicking a CELL DOOR.
		"Speed Increase Per Pick For Breaking Cell Doors" = 14
		#How much progress is gained on a successfull pick when lockpicking a SAFES.
		"Progress Per Pick For Breaking Safes" = 3
		#How much the progress-loss speeds up per pick when lockpicking a SAFES.
		"Speed Increase Per Pick For Breaking Safes" = 10

	["cuffed Config"."Restraint Durabilities"]
		#The amount of durability handcuffs have.
		"Handcuffs Durability" = 40
		#The amount of durability fuzzy handcuffs have.
		"Fuzzy Handcuffs Durability" = 30
		#The amount of durability shackles have.
		"Shackles Durability" = 15

	["cuffed Config"."Handcuffs when on Arms"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = false
		#Whether or not this restraint is lockpickable.
		Lockpickable = true
		#The amount of progress gained per pick when lockpicking this restraint.
		"Lockpicking Progresss Per Pick" = 6
		#The speed increase per pick when lockpicking this restraint.
		"Lockpicking Speed Increase Per Pick" = 12

	["cuffed Config"."Fuzzy Handcuffs when on Arms"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = true
		#Whether or not this restraint is lockpickable.
		Lockpickable = true
		#The amount of progress gained per pick when lockpicking this restraint.
		"Lockpicking Progresss Per Pick" = 6
		#The speed increase per pick when lockpicking this restraint.
		"Lockpicking Speed Increase Per Pick" = 14

	["cuffed Config"."Shackles when on Arms"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = false
		#Whether or not this restraint is lockpickable.
		Lockpickable = true
		#The amount of progress gained per pick when lockpicking this restraint.
		"Lockpicking Progresss Per Pick" = 8
		#The speed increase per pick when lockpicking this restraint.
		"Lockpicking Speed Increase Per Pick" = 10

	["cuffed Config"."Duck Tape when on Arms"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = false
		#The total durability of this restraint when breaking out of it.
		Durability = 5

	["cuffed Config"."Handcuffs when on Legs"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = false
		#Whether or not this restraint is lockpickable.
		Lockpickable = true
		#The amount of progress gained per pick when lockpicking this restraint.
		"Lockpicking Progresss Per Pick" = 6
		#The speed increase per pick when lockpicking this restraint.
		"Lockpicking Speed Increase Per Pick" = 12

	["cuffed Config"."Shackles when on Legs"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = false
		#Whether or not this restraint is lockpickable.
		Lockpickable = true
		#The amount of progress gained per pick when lockpicking this restraint.
		"Lockpicking Progresss Per Pick" = 8
		#The speed increase per pick when lockpicking this restraint.
		"Lockpicking Speed Increase Per Pick" = 10

	["cuffed Config"."Duck Tape when on Legs"]
		#Whether or not this restraint can be broken out of.
		"Can Be Broken Out Of" = true
		#Whether or not to drop the item when broken out of.
		"Drop Item When Broken" = false
		#The total durability of this restraint when breaking out of it.
		Durability = 5

