
[general]
	#Force creation of canoes from specified wood types. Turning this to false will make canoes craftable from any wood type.
	canoeWoodRestriction = true
	#Force creation of ships and rowboats from specified wood types. Turning this to false will make ships and rowboats craftable from any wood type.
	shipWoodRestriction = true
	#Force reduceDebugInfo gamerule. Turn this to FALSE if you want coordinates back.
	forceReducedDebugInfo = false
	#Disables vanilla boats and base TFC boats from working.
	disableVanillaBoatFunctionality = true
	#Automatically adjusts latitude and longitude to match the climate scale of the TFC world.
	changeLatitudeLongitudeBasedOnClimateConfig = true
	#Expands water source creation to make canal building possible at sea level.
	enableParallelSourceCreationAtSeaLevel = true

