
["Container Item Config"]

	["Container Item Config"."Straw Basket"]
		#Determines if this container will automatically pickup items
		doPickup = true
		#Determines if this container can void items on pickup
		doVoiding = true
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = true
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 4
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 32
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "SMALL"

	["Container Item Config"."Leather Sack"]
		#Determines if this container will automatically pickup items
		doPickup = false
		#Determines if this container can void items on pickup
		doVoiding = false
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = true
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 4
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 64
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "NORMAL"

	["Container Item Config"."Burlap Sack"]
		#Determines if this container will automatically pickup items
		doPickup = true
		#Determines if this container can void items on pickup
		doVoiding = true
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = false
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 8
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 48
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "SMALL"

	["Container Item Config"."Ore Sack"]
		#Determines if this container will automatically pickup items
		doPickup = true
		#Determines if this container can void items on pickup
		doVoiding = false
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = true
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 1
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 512
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "SMALL"

	["Container Item Config"."Seed Pouch"]
		#Determines if this container will automatically pickup items
		doPickup = true
		#Determines if this container can void items on pickup
		doVoiding = false
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = true
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 27
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 64
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "SMALL"

	["Container Item Config"."Frame Pack"]
		#Determines if this container will automatically pickup items
		doPickup = false
		#Determines if this container can void items on pickup
		doVoiding = false
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = false
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 18
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 64
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "LARGE"

	["Container Item Config"."Lunch Box"]
		#Determines if this container will automatically pickup items
		doPickup = false
		#Determines if this container can void items on pickup
		doVoiding = false
		#Determines if this container can transfer items in an inventory
		doInventoryTransfer = true
		#This config has a realistic cap of 27 as any higher the slots are added on top of the player slots
		#Range: 1 ~ 27
		slotCount = 8
		#Item stack max for the type of container
		#Range: 1 ~ 512
		slotCap = 4
		#The maximum item size allowed in the container
		#Allowed Values: TINY, VERY_SMALL, SMALL, NORMAL, LARGE, VERY_LARGE, HUGE
		allowedSize = "NORMAL"

["Global config"]
	#Global control for automatic pickup, this will not force enable for every type
	doPickup = true
	#A global toggle for item voiding, this will not force enable for every type
	doVoiding = true
	#Enable auto pickup for other container like items such as the TFC vessel.
	#This may not always work as expected enable at your own discretion
	allPickup = false
	#This allows other containers such as vessels to support the pick block search
	allPickBlock = false
	#This makes all container types capable of holding ore
	allAllowOre = false
	#This makes all container types capable of holding food although they won't preserve it!
	allAllowFood = false
	#This allows containers to have items inserted and extracted from them via the inventory like vanilla Bundles
	enableContainerInventoryInteraction = true
	#The modifer for the 'Lunchbox' food trait. Values less than 1 extend food lifetime, values greater than one decrease it. A value of zero stops decay.
	#Range: 0.0 ~ 1.7976931348623157E308
	traitLunchboxModifier = 0.6
	#The maximum size of an entity which mob nets can capture. This is not directly related to TFC's animal size stat.
	#Range: 0.0 ~ 1.7976931348623157E308
	maximumNetCaptureSize = 0.5

