StartupEvents.registry('block', (event) => {
	event.create('copper_mantle_ore')
        .displayName('Copper Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')

    event.create('gold_mantle_ore')
        .displayName('Gold Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')

    event.create('silver_mantle_ore')
        .displayName('Silver Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
    
    event.create('tin_mantle_ore')
        .displayName('Tin Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
    
    event.create('bismuth_mantle_ore')
        .displayName('Bismuth Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')

    event.create('nickel_mantle_ore')
        .displayName('Nickel Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')

    event.create('iron_mantle_ore')
        .displayName('Iron Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')

    event.create('zinc_mantle_ore')
        .displayName('Zinc Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
    
    event.create('cryolite_mantle_ore')
        .displayName('Cryolite Mantle Ore')
        .soundType('tuff')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
});
